# Generated by Django 5.0.7 on 2024-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('placed_section_id', models.TextField()),
                ('price', models.IntegerField()),
                ('finishing_date', models.DateField()),
                ('stocked_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('placed_section_id', models.TextField()),
                ('price', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('stocked_time', models.IntegerField()),
            ],
        ),
    ]
