# Generated by Django 5.0.7 on 2024-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('payroll', models.IntegerField()),
                ('performance_eval', models.CharField(max_length=50)),
                ('bonus', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('training_duration_months', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManufactureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('quality_control', models.TextField()),
                ('starting_date', models.DateField()),
                ('expected_finishing_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quality', models.TextField()),
                ('buyer_name', models.CharField(max_length=50)),
                ('purchasing_date', models.DateField()),
            ],
        ),
    ]
