# Generated by Django 5.0.7 on 2024-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('enquiry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('social_media', models.CharField(blank=True, default='', max_length=30)),
                ('feedback', models.TextField(blank=True, default='', max_length=300)),
                ('purchased_item', models.TextField()),
                ('gender', models.TextField(blank=True, default='')),
            ],
        ),
    ]
